#!/usr/bin/env python3
"""Verify that a personal-edition knowledge base landed in the enterprise stack (B-15).

``scripts/migrate_kb.py`` reconciles the source and (with ``--apply``) imports it;
this is the read-only counterpart that checks the result afterwards, per base,
without asking a model provider for anything:

* **chunk counting** — the source index's chunk count per document against the
  enterprise ``workbuddy_knowledge_documents.chunk_count``, aligned by document
  title (the name a migrated document inherits from the personal control plane's
  ``knowledge_documents`` row); a document that is missing from the target base or
  whose count differs is listed either way;
* **self-retrieval** — a sample of the source's own chunk vectors is used as the
  probe: the nearest neighbours the source index returns must be the same chunks
  the enterprise base returns for that probe.  Ids are regenerated by the import,
  so chunks are compared by their text prefix, and both sides use the same
  embedder (the one that produced the stored vectors), so no model is needed.  A
  probe whose k-th neighbour ties with the next one is skipped and counted as
  ``tied``: both sides may fill that last slot with either chunk, so such a
  disagreement would not be a migration defect.

Nothing here writes to the source index, the personal control plane, or the
enterprise database; re-running is safe and yields the same report.  The report
goes to stdout (``--quiet`` prints only the JSON) and to ``--report`` as JSON, and
the exit code is non-zero as soon as a difference or an error was recorded.

Usage:

    python scripts/verify_kb_migration.py --target-db postgresql://user:pass@host/db \
        --tenant-id <uuid> --report verification.json

Same source arguments as ``scripts/migrate_kb.py`` (``--source-dir``,
``--source-db``); the helpers that read them are imported from that script rather
than duplicated.
"""

from __future__ import annotations

import argparse
import json
import math
import sqlite3
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:  # ``scripts/`` is not an importable package
    sys.path.insert(0, str(_SCRIPT_DIR))

import migrate_kb  # noqa: E402 - imported after scripts/ is on sys.path

#: Chunks are identified across the two sides by this many characters of text:
#: the import regenerates chunk ids and may renumber ordinals, the text stays.
PREFIX_LENGTH = 48

#: How many source chunks are probed by default, and how many neighbours are
#: compared per probe.  The enterprise search caps its own result set at 50.
DEFAULT_SAMPLE = 5
DEFAULT_TOP_K = 5
MAX_TOP_K = 50

#: The enterprise knowledge tables fix the embedding dimension at 1024.
ENTERPRISE_DIMENSIONS = migrate_kb.ENTERPRISE_DIMENSIONS

#: Document sources that a migration produces; used to spot target-only rows.
MIGRATED_DOCUMENT_SOURCES = ("migration", "text")

#: Two neighbour scores this close are the same score.  When the k-th and the
#: (k+1)-th neighbour tie, each side may fill the last slot with either chunk, so
#: the probe says nothing about the migration and is skipped rather than reported.
TIE_EPSILON = 1e-6


@dataclass(slots=True)
class SourceChunk:
    """One chunk of the personal index, with its vector decoded."""

    doc_id: str
    ordinal: int
    text: str
    embedding: list[float]


def read_source_chunks(index_path: Path) -> tuple[list[SourceChunk], str]:
    """Every chunk of one personal base, vectors decoded; ``(chunks, error)``.

    Read-only through :func:`migrate_kb._connect_readonly` and ordered by
    ``(doc_id, ordinal)`` so the probe sample is deterministic.  A truncated or
    foreign file is an error for this base only — the run continues.
    """
    if not index_path.exists():
        return [], "index.sqlite is missing"
    try:
        with migrate_kb._connect_readonly(index_path) as connection:
            rows = connection.execute(
                "SELECT doc_id, ordinal, text, embedding FROM chunks ORDER BY doc_id, ordinal"
            ).fetchall()
    except sqlite3.Error as exc:
        return [], f"unreadable index: {exc}"
    chunks: list[SourceChunk] = []
    for row in rows:
        try:
            embedding = migrate_kb.decode_embedding(bytes(row["embedding"]))
        except ValueError as exc:
            return chunks, f"chunk {row['doc_id']} #{row['ordinal']}: {exc}"
        chunks.append(
            SourceChunk(
                doc_id=str(row["doc_id"]),
                ordinal=int(row["ordinal"]),
                text=str(row["text"]),
                embedding=embedding,
            )
        )
    return chunks, ""


def read_source_titles(db_path: Path) -> dict[str, str]:
    """``document_id -> title`` as the personal control plane names documents.

    The index sidecar keeps no title, so the control plane is the only place the
    name a migrated document inherits lives.  A control plane without the table
    (or without it readable) yields no titles; the caller then reports the
    document check as unverifiable instead of guessing a pairing.
    """
    if not db_path.exists():
        return {}
    try:
        with migrate_kb._connect_readonly(db_path) as connection:
            rows = connection.execute(
                "SELECT document_id, filename, path FROM knowledge_documents"
            ).fetchall()
    except sqlite3.Error:
        return {}
    titles: dict[str, str] = {}
    for row in rows:
        name = str(row["filename"] or row["path"] or row["document_id"])
        titles[str(row["document_id"])] = name
    return titles


class TargetDatabase:
    """Read-only enterprise-side reader for one tenant (PostgreSQL)."""

    def __init__(self, database: str, tenant_id: str) -> None:
        from octop.infra.db.pool import PostgresPool
        from octop.infra.db.repos.workbuddy_knowledge import WorkBuddyKnowledgeRepo
        from octop.infra.db.workbuddy_context import WorkBuddyDbContext

        self._pool = PostgresPool(database, min_size=1, max_size=1)
        self._repo = WorkBuddyKnowledgeRepo(self._pool)
        self._ctx = WorkBuddyDbContext.for_tenant(tenant_id)

    def close(self) -> None:
        self._pool.close()

    def bases(self) -> list[Any]:
        """Every live base of the tenant, newest first."""
        return list(self._repo.list_bases(self._ctx))

    def documents(self, kb_id: str) -> list[Any]:
        """Every document of one base, deleted rows included."""
        return list(self._repo.list_documents(self._ctx, kb_id, include_deleted=True))

    def neighbours(self, kb_id: str, vector: list[float], limit: int) -> list[Any]:
        """The retrievable chunks nearest to one probe vector (cosine)."""
        return list(
            self._repo.search_chunks(self._ctx, kb_id, query_vector=vector, limit=limit)
        )


def _normalise(title: str) -> str:
    """Case- and whitespace-insensitive title key for the alignment."""
    return " ".join(title.split()).casefold()


def _prefix(text: str) -> str:
    """Whitespace-normalised text prefix: the cross-side chunk identity."""
    return " ".join(text.split())[:PREFIX_LENGTH]


def _cosine(left: list[float], right: list[float]) -> float:
    """Cosine similarity; ``0.0`` when either side has no direction."""
    if len(left) != len(right):
        return 0.0
    dot = sum(a * b for a, b in zip(left, right, strict=True))
    left_norm = math.sqrt(sum(value * value for value in left))
    right_norm = math.sqrt(sum(value * value for value in right))
    if not left_norm or not right_norm:
        return 0.0
    return dot / (left_norm * right_norm)


def _scored_chunks(
    chunks: list[SourceChunk], probe: list[float]
) -> list[tuple[float, SourceChunk]]:
    """Every source chunk with its similarity to ``probe``, closest first.

    The whole ranking is returned, not just the first ``top_k``: the chunk that
    was left out is what tells a comparison whether its last slot was decided by
    a tie.  Equal scores are ordered by position so the ranking is deterministic.
    """
    scored = [(_cosine(probe, chunk.embedding), chunk) for chunk in chunks]
    scored.sort(key=lambda item: (-item[0], item[1].doc_id, item[1].ordinal))
    return scored


def _sample_chunks(chunks: list[SourceChunk], sample: int) -> list[SourceChunk]:
    """``sample`` chunks spread evenly over the base, deterministically."""
    if sample <= 0 or not chunks:
        return []
    step = max(1, len(chunks) // sample)
    return chunks[::step][:sample]


def _counts_by_doc(chunks: list[SourceChunk]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for chunk in chunks:
        counts[chunk.doc_id] = counts.get(chunk.doc_id, 0) + 1
    return counts


def _match_target_base(
    bases: list[Any], base: migrate_kb.SourceBase
) -> tuple[Any | None, str, bool]:
    """``(row, how, ambiguous)`` for the tenant twin of one personal base.

    The mirror matches by creator and name (``knowledge_adapter.mirror_base``);
    the same rule is applied here, with a name-only fallback so a base imported
    by an administrator can still be verified.  Ambiguity is reported, never
    silently resolved.
    """
    named = [row for row in bases if row.name == base.name]
    if not named:
        return None, "missing", False
    by_creator = [row for row in named if row.created_by_user_id == base.owner_user_id]
    if by_creator:
        return by_creator[0], "creator+name", len(by_creator) > 1
    return named[0], "name", len(named) > 1


def _preferred_document(candidates: list[Any]) -> Any | None:
    """The migrated twin among documents sharing a title, newest first."""
    for row in candidates:
        if row.source in MIGRATED_DOCUMENT_SOURCES:
            return row
    return candidates[0] if candidates else None


def _verify_documents(
    *,
    counts: dict[str, int],
    titles: dict[str, str],
    live_documents: list[Any],
) -> tuple[dict[str, Any], list[str], int]:
    """Compare per-document chunk counts; ``(section, notes, matched_chunks)``."""
    section: dict[str, Any] = {
        "source": len(counts),
        "matched": 0,
        "aligned_by": "title",
        "missing": [],
        "mismatched": [],
        "extra": [],
        "skipped": "",
    }
    notes: list[str] = []
    if not counts:
        return section, notes, 0
    if not titles:
        section["skipped"] = "the personal control plane holds no document titles"
        notes.append(
            "document titles are unavailable, so chunk counts could not be aligned per document"
        )
        return section, notes, 0

    by_title: dict[str, list[Any]] = {}
    for document in live_documents:
        by_title.setdefault(_normalise(document.title), []).append(document)

    source_titles = {doc_id: titles.get(doc_id, doc_id) for doc_id in counts}
    aligned_by_doc_id = [doc_id for doc_id in counts if doc_id not in titles]
    if aligned_by_doc_id:
        section["aligned_by"] = "title/doc_id"
        notes.append(
            f"{len(aligned_by_doc_id)} source document(s) carry no control-plane title "
            "and were aligned by id"
        )
    matched_chunks = 0
    for doc_id, source_chunks in sorted(counts.items()):
        title = source_titles[doc_id]
        document = _preferred_document(by_title.get(_normalise(title), []))
        if document is None:
            section["missing"].append(
                {"doc_id": doc_id, "title": title, "chunks": source_chunks}
            )
            continue
        section["matched"] += 1
        matched_chunks += int(document.chunk_count)
        if int(document.chunk_count) != source_chunks:
            section["mismatched"].append(
                {
                    "doc_id": doc_id,
                    "title": title,
                    "target_document_id": document.document_id,
                    "source_chunks": source_chunks,
                    "target_chunks": int(document.chunk_count),
                }
            )
    source_keys = {_normalise(title) for title in source_titles.values()}
    for document in live_documents:
        if document.source in MIGRATED_DOCUMENT_SOURCES and _normalise(document.title) not in source_keys:
            section["extra"].append(
                {
                    "title": document.title,
                    "document_id": document.document_id,
                    "source": document.source,
                    "chunks": int(document.chunk_count),
                }
            )
    return section, notes, matched_chunks


def _verify_retrieval(
    *,
    chunks: list[SourceChunk],
    target: TargetDatabase,
    kb_id: str,
    sample: int,
    top_k: int,
) -> tuple[dict[str, Any], list[str], list[str]]:
    """Self-retrieval: the source's own vectors as probes against both sides.

    ``(section, notes, differences)`` — a difference is a probe whose neighbour
    set does not match, reported with the prefixes that were missing or extra.
    """
    section: dict[str, Any] = {
        "sampled": 0,
        "compared": 0,
        "tied": 0,
        "top_k": top_k,
        "hit_rate": None,
        "probes": [],
        "skipped": "",
    }
    probes = _sample_chunks(chunks, sample)
    section["sampled"] = len(probes)
    if not probes:
        section["skipped"] = "the source index holds no chunks to probe"
        return section, [], []
    dimensions = sorted({len(probe.embedding) for probe in probes})
    if dimensions != [ENTERPRISE_DIMENSIONS]:
        section["skipped"] = (
            f"source vectors are {dimensions}-dimensional, the enterprise column is "
            f"{ENTERPRISE_DIMENSIONS}"
        )
        return section, [section["skipped"]], []

    differences: list[str] = []
    notes: list[str] = []
    shared_total = 0
    available_total = 0
    compared = 0
    for probe in probes:
        scored = _scored_chunks(chunks, probe.embedding)
        neighbours = scored[:top_k]
        boundary = neighbours[-1][0] if neighbours else 0.0
        tied = sum(1 for score, _ in scored if abs(score - boundary) <= TIE_EPSILON)
        if len(neighbours) == top_k and tied > 1:
            # The last of the k neighbours is decided by a tie, not by the vectors:
            # pgvector and the source index may each return either of the tied
            # chunks, so a disagreement here would not be a migration defect.
            section["tied"] += 1
            notes.append(
                f"probe {probe.doc_id} #{probe.ordinal}: the last of {top_k} neighbours is tied "
                f"with {tied - 1} other chunk(s); the comparison was skipped"
            )
            continue
        source_set = {_prefix(chunk.text) for _, chunk in neighbours}
        target_set = {_prefix(hit.content) for hit in target.neighbours(kb_id, probe.embedding, top_k)}
        shared = source_set & target_set
        missing = sorted(source_set - target_set)
        unexpected = sorted(target_set - source_set)
        compared += 1
        shared_total += len(shared)
        # A base holding fewer chunks than ``top_k`` can only offer what it has:
        # the denominator is what the source side actually returned.
        available_total += len(source_set)
        section["probes"].append(
            {
                "document": probe.doc_id,
                "ordinal": probe.ordinal,
                "prefix": _prefix(probe.text),
                "shared": len(shared),
                "of": len(source_set),
                "missing": missing,
                "unexpected": unexpected,
            }
        )
        if missing or unexpected:
            differences.append(
                f"probe {probe.doc_id} #{probe.ordinal}: {len(shared)}/{len(source_set)} "
                f"neighbours shared; missing {missing}; unexpected {unexpected}"
            )
    section["compared"] = compared
    section["hit_rate"] = (
        round(shared_total / available_total, 4) if available_total else None
    )
    return section, notes, differences


def _verify_base(
    base: migrate_kb.SourceBase,
    *,
    source_dir: Path,
    titles: dict[str, str],
    target: TargetDatabase | None,
    target_bases: list[Any],
    sample: int,
    top_k: int,
) -> tuple[dict[str, Any], list[dict[str, Any]], list[str]]:
    """One base's report entry, its differences, and its errors."""
    entry: dict[str, Any] = {
        "kb_id": base.kb_id,
        "name": base.name,
        "owner_user_id": base.owner_user_id,
        "target_scope": base.target_scope,
        "target_kb_id": "",
        "target_match": "unchecked",
        "documents": {},
        "chunks": {"source": 0, "target": 0, "matched": 0},
        "retrieval": {},
        "notes": [],
        "ok": False,
    }
    differences: list[dict[str, Any]] = []
    errors: list[str] = []

    chunks, source_error = read_source_chunks(source_dir / base.kb_id / "index.sqlite")
    if source_error:
        errors.append(f"{base.kb_id}: {source_error}")
        entry["notes"].append(source_error)
        return entry, differences, errors

    entry["chunks"]["source"] = len(chunks)
    counts = _counts_by_doc(chunks)

    if target is None:
        entry["documents"] = {
            "source": len(counts),
            "matched": 0,
            "aligned_by": "title",
            "missing": [],
            "mismatched": [],
            "extra": [],
            "skipped": "there is no checked target base",
        }
        entry["retrieval"] = {
            "sampled": len(_sample_chunks(chunks, sample)),
            "compared": 0,
            "tied": 0,
            "top_k": top_k,
            "hit_rate": None,
            "probes": [],
            "skipped": "there is no checked target base",
        }
        return entry, differences, errors

    row, matched_by, ambiguous = _match_target_base(target_bases, base)
    entry["target_match"] = matched_by
    if row is None:
        differences.append(
            {
                "kb_id": base.kb_id,
                "kind": "base_missing",
                "detail": f"no target base is named {base.name!r}",
            }
        )
        return entry, differences, errors
    entry["target_kb_id"] = row.kb_id
    if ambiguous:
        differences.append(
            {
                "kb_id": base.kb_id,
                "kind": "base_ambiguous",
                "detail": f"more than one target base matches {base.name!r}; "
                f"{row.kb_id} (created by user {row.created_by_user_id}) was used",
            }
        )
    entry["notes"].append(f"target base matched by {matched_by}")

    try:
        documents = target.documents(row.kb_id)
    except Exception as exc:  # a report must survive one unreadable base
        errors.append(f"{base.kb_id}: target documents: {type(exc).__name__}: {exc}")
        return entry, differences, errors

    live = [document for document in documents if document.deleted_at is None]
    entry["chunks"]["target"] = sum(int(document.chunk_count) for document in live)

    section, notes, matched_chunks = _verify_documents(
        counts=counts, titles=titles, live_documents=live
    )
    entry["documents"] = section
    entry["chunks"]["matched"] = matched_chunks
    entry["notes"].extend(notes)
    for document in section["missing"]:
        differences.append(
            {
                "kb_id": base.kb_id,
                "kind": "document_missing",
                "detail": f"{document['title']!r} ({document['chunks']} source chunks) is "
                f"not in the target base",
            }
        )
    for document in section["mismatched"]:
        differences.append(
            {
                "kb_id": base.kb_id,
                "kind": "document_chunks",
                "detail": f"{document['title']!r}: source {document['source_chunks']} chunks, "
                f"target {document['target_chunks']}",
            }
        )
    for document in section["extra"]:
        differences.append(
            {
                "kb_id": base.kb_id,
                "kind": "document_extra",
                "detail": f"{document['title']!r} ({document['source']}) has no source document",
            }
        )
    if section["skipped"]:
        errors.append(f"{base.kb_id}: {section['skipped']}")

    try:
        retrieval, retrieval_notes, retrieval_differences = _verify_retrieval(
            chunks=chunks, target=target, kb_id=row.kb_id, sample=sample, top_k=top_k
        )
    except Exception as exc:  # the target side may fail per probe
        errors.append(f"{base.kb_id}: target retrieval: {type(exc).__name__}: {exc}")
        retrieval, retrieval_notes, retrieval_differences = {}, [], []
    entry["retrieval"] = retrieval
    entry["notes"].extend(retrieval_notes)
    for detail in retrieval_differences:
        differences.append({"kb_id": base.kb_id, "kind": "retrieval", "detail": detail})
    if retrieval.get("skipped"):
        errors.append(f"{base.kb_id}: retrieval sample skipped: {retrieval['skipped']}")

    entry["ok"] = not differences
    return entry, differences, errors


def _totals(entries: list[dict[str, Any]]) -> dict[str, Any]:
    documents = {"source": 0, "matched": 0, "missing": 0, "mismatched": 0, "extra": 0}
    chunks = {"source": 0, "target": 0, "matched": 0}
    sampled = compared = tied = shared = available = 0
    for entry in entries:
        documents["source"] += entry["documents"].get("source", 0)
        documents["matched"] += entry["documents"].get("matched", 0)
        for key in ("missing", "mismatched", "extra"):
            documents[key] += len(entry["documents"].get(key, []))
        chunks["source"] += entry["chunks"].get("source", 0)
        chunks["target"] += entry["chunks"].get("target", 0)
        chunks["matched"] += entry["chunks"].get("matched", 0)
        retrieval = entry["retrieval"]
        sampled += retrieval.get("sampled", 0)
        compared += retrieval.get("compared", 0)
        tied += retrieval.get("tied", 0)
        for probe in retrieval.get("probes", []):
            shared += probe.get("shared", 0)
            available += probe.get("of", 0)
    return {
        "knowledge_bases": len(entries),
        "verified": sum(1 for entry in entries if entry["ok"]),
        "documents": documents,
        "chunks": chunks,
        "retrieval": {
            "sampled": sampled,
            "compared": compared,
            "tied": tied,
            "hit_rate": round(shared / available, 4) if available else None,
        },
    }


def verify(
    *,
    source_dir: Path,
    source_db: Path,
    target_db: str | None,
    tenant_id: str | None,
    sample: int = DEFAULT_SAMPLE,
    top_k: int = DEFAULT_TOP_K,
) -> dict[str, Any]:
    """Read both sides and report every discrepancy; writes nothing."""
    effective_top_k = max(1, min(int(top_k), MAX_TOP_K))
    report: dict[str, Any] = {
        "source_dir": str(source_dir),
        "source_db": str(source_db),
        "target": {
            "database": target_db or "",
            "tenant_id": tenant_id or "",
            "checked": False,
            "error": "",
        },
        "options": {
            "sample": max(1, int(sample)),
            "top_k": effective_top_k,
            "prefix_length": PREFIX_LENGTH,
        },
        "knowledge_bases": [],
        "totals": {},
        "differences": [],
        "errors": [],
    }
    differences: list[dict[str, Any]] = report["differences"]
    errors: list[str] = report["errors"]

    target: TargetDatabase | None = None
    target_bases: list[Any] = []
    try:
        if not target_db or not tenant_id:
            errors.append(
                "no target database and tenant were given, so nothing could be verified"
            )
        else:
            try:
                target = TargetDatabase(str(target_db), str(tenant_id))
                target_bases = target.bases()
                report["target"]["checked"] = True
            except Exception as exc:
                target = None
                report["target"]["error"] = f"{type(exc).__name__}: {exc}"
                errors.append(f"target database: {report['target']['error']}")

        try:
            bases = migrate_kb.read_source_bases(source_db)
        except (FileNotFoundError, sqlite3.Error) as exc:
            errors.append(f"source control plane: {exc}")
            bases = []
        titles = read_source_titles(source_db) if bases else {}

        for base in bases:
            entry, base_differences, base_errors = _verify_base(
                base,
                source_dir=source_dir,
                titles=titles,
                target=target,
                target_bases=target_bases,
                sample=report["options"]["sample"],
                top_k=effective_top_k,
            )
            report["knowledge_bases"].append(entry)
            differences.extend(base_differences)
            errors.extend(base_errors)
    finally:
        if target is not None:
            target.close()

    report["totals"] = _totals(report["knowledge_bases"])
    return report


def _summarise(report: dict[str, Any]) -> str:
    lines = [
        f"source: {report['source_db']} + {report['source_dir']}",
        f"target: {report['target']['database'] or '(none)'} "
        f"checked={report['target']['checked']}",
    ]
    if report["target"]["error"]:
        lines.append(f"target error: {report['target']['error']}")
    for entry in report["knowledge_bases"]:
        documents = entry["documents"]
        retrieval = entry["retrieval"]
        hit_rate = retrieval.get("hit_rate")
        lines.append(
            f"  {entry['kb_id']}  {entry['name']!r}"
            f"  target={entry['target_kb_id'] or '(none)'} via {entry['target_match']}"
            f"  documents {documents.get('matched', 0)}/{documents.get('source', 0)} matched"
            f"  chunks source={entry['chunks']['source']} target={entry['chunks']['target']}"
            f"  probes {retrieval.get('compared', 0)}/{retrieval.get('sampled', 0)}"
            f" (tied {retrieval.get('tied', 0)})"
            f"  hit_rate={hit_rate}"
        )
    totals = report["totals"]
    lines.append(
        f"totals: {totals['knowledge_bases']} bases ({totals['verified']} verified), "
        f"documents {totals['documents']}, chunks {totals['chunks']}, "
        f"retrieval {totals['retrieval']}"
    )
    for difference in report["differences"]:
        lines.append(f"difference [{difference['kind']}] {difference['kb_id']}: {difference['detail']}")
    for error in report["errors"]:
        lines.append(f"error: {error}")
    return "\n".join(lines)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Verify that a personal-edition knowledge migration landed in the enterprise "
            "tables: per-document chunk counts and a self-retrieval probe built from the "
            "source's own vectors. Read-only on both sides; a non-zero exit code means a "
            "difference or an error was reported."
        )
    )
    parser.add_argument(
        "--source-dir",
        default=str(Path.home() / ".octop" / "knowledge"),
        help="directory holding one <kb_id>/index.sqlite per base",
    )
    parser.add_argument(
        "--source-db",
        default=str(Path.home() / ".octop" / "octop.db"),
        help="the personal control-plane SQLite database (knowledge_bases table)",
    )
    parser.add_argument(
        "--target-db",
        default="",
        help="enterprise PostgreSQL DSN; without it (and --tenant-id) nothing is verified",
    )
    parser.add_argument("--tenant-id", default="", help="enterprise tenant holding the bases")
    parser.add_argument(
        "--sample",
        type=int,
        default=DEFAULT_SAMPLE,
        help=f"source chunks used as retrieval probes, at least 1 (default {DEFAULT_SAMPLE})",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=DEFAULT_TOP_K,
        help=f"neighbours compared per probe, at most {MAX_TOP_K} (default {DEFAULT_TOP_K})",
    )
    parser.add_argument("--report", default="", help="write the report as JSON to this path")
    parser.add_argument("--quiet", action="store_true", help="write only the JSON report")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    report = verify(
        source_dir=Path(args.source_dir).expanduser(),
        source_db=Path(args.source_db).expanduser(),
        target_db=args.target_db.strip() or None,
        tenant_id=args.tenant_id.strip() or None,
        sample=args.sample,
        top_k=args.top_k,
    )
    if args.report:
        Path(args.report).expanduser().write_text(
            json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
    if not args.quiet:
        print(_summarise(report))
    else:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    # A difference or an error is what the operator has to act on; a clean run is 0.
    return 1 if report["differences"] or report["errors"] else 0


if __name__ == "__main__":  # pragma: no cover - script entry point
    sys.exit(main())
