"""Stable error codes and the typed exception that crosses API boundaries."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from octop.i18n import error_message as i18n_error_message
from octop.infra.utils.locale import Locale, normalize_locale


class ErrorCode(StrEnum):
    AUTH_FAILED = "AUTH_FAILED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    SETUP_REQUIRED = "SETUP_REQUIRED"
    DATABASE_NOT_EMPTY = "DATABASE_NOT_EMPTY"
    BACKUP_DRIVER_MISMATCH = "BACKUP_DRIVER_MISMATCH"
    BACKUP_SCHEMA_INCOMPATIBLE = "BACKUP_SCHEMA_INCOMPATIBLE"
    BACKUP_IN_PROGRESS = "BACKUP_IN_PROGRESS"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    USER_DISABLED = "USER_DISABLED"
    LOGIN_LOCKED = "LOGIN_LOCKED"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    EMAIL_INVALID = "EMAIL_INVALID"
    PASSWORD_SAME_AS_OLD = "PASSWORD_SAME_AS_OLD"
    PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"
    SETUP_PASSWORD_WRONG = "SETUP_PASSWORD_WRONG"
    SETUP_RATE_LIMITED = "SETUP_RATE_LIMITED"
    SETUP_TOKEN_INVALID = "SETUP_TOKEN_INVALID"
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_NOT_RUNNING = "AGENT_NOT_RUNNING"
    AGENT_FAILED = "AGENT_FAILED"
    AGENT_BUSY = "AGENT_BUSY"
    AGENT_NAME_TAKEN = "AGENT_NAME_TAKEN"
    AGENT_ID_INVALID = "AGENT_ID_INVALID"
    AGENT_ID_TAKEN = "AGENT_ID_TAKEN"
    PROVIDER_NAME_TAKEN = "PROVIDER_NAME_TAKEN"
    PROVIDER_NOT_VISIBLE = "PROVIDER_NOT_VISIBLE"
    PROVIDER_REFERENCED = "PROVIDER_REFERENCED"
    PROVIDER_LOCAL_PROTECTED = "PROVIDER_LOCAL_PROTECTED"
    STORAGE_BACKEND_NAME_TAKEN = "STORAGE_BACKEND_NAME_TAKEN"
    STORAGE_BACKEND_REFERENCED = "STORAGE_BACKEND_REFERENCED"
    STORAGE_BACKEND_DEPS_FAILED = "STORAGE_BACKEND_DEPS_FAILED"
    CHANNEL_KIND_UNSUPPORTED = "CHANNEL_KIND_UNSUPPORTED"
    CHANNEL_INVALID_CREDENTIALS = "CHANNEL_INVALID_CREDENTIALS"
    CHANNEL_NAME_TAKEN = "CHANNEL_NAME_TAKEN"
    CONNECTOR_NOT_FOUND = "CONNECTOR_NOT_FOUND"
    CONNECTOR_NAME_TAKEN = "CONNECTOR_NAME_TAKEN"
    CONNECTOR_INVALID_CREDENTIALS = "CONNECTOR_INVALID_CREDENTIALS"
    CONNECTOR_OAUTH_HTTPS_REQUIRED = "CONNECTOR_OAUTH_HTTPS_REQUIRED"
    CONNECTOR_KIND_UNSUPPORTED = "CONNECTOR_KIND_UNSUPPORTED"
    CONNECTOR_NOT_BOUND = "CONNECTOR_NOT_BOUND"
    CONNECTOR_ALREADY_BOUND = "CONNECTOR_ALREADY_BOUND"
    CONNECTOR_MCP_LOAD_FAILED = "CONNECTOR_MCP_LOAD_FAILED"
    CRON_TRIGGER_INVALID = "CRON_TRIGGER_INVALID"
    SLASH_UNKNOWN = "SLASH_UNKNOWN"
    SLASH_BAD_ARGS = "SLASH_BAD_ARGS"
    ATTACHMENT_UNSUPPORTED_TYPE = "ATTACHMENT_UNSUPPORTED_TYPE"
    ATTACHMENT_TOO_LARGE = "ATTACHMENT_TOO_LARGE"
    VOICE_BROWSER_ONLY = "VOICE_BROWSER_ONLY"
    VOICE_KIND_UNSUPPORTED = "VOICE_KIND_UNSUPPORTED"
    VOICE_CAPABILITY_MISMATCH = "VOICE_CAPABILITY_MISMATCH"
    VOICE_PROVIDER_DISABLED = "VOICE_PROVIDER_DISABLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    TLS_NOT_ELIGIBLE = "TLS_NOT_ELIGIBLE"
    TLS_ISSUE_IN_PROGRESS = "TLS_ISSUE_IN_PROGRESS"
    TLS_DOMAIN_MISMATCH = "TLS_DOMAIN_MISMATCH"
    WORKSPACE_OP_UNSUPPORTED = "WORKSPACE_OP_UNSUPPORTED"
    SKILL_IMPORT_UNSUPPORTED_URL = "SKILL_IMPORT_UNSUPPORTED_URL"
    SKILL_IMPORT_FAILED = "SKILL_IMPORT_FAILED"
    SKILL_ALREADY_EXISTS = "SKILL_ALREADY_EXISTS"
    SKILL_PACKAGE_NOT_FOUND = "SKILL_PACKAGE_NOT_FOUND"
    SKILL_PACKAGE_NAME_TAKEN = "SKILL_PACKAGE_NAME_TAKEN"
    SKILL_PACKAGE_BACKEND_UNSUPPORTED = "SKILL_PACKAGE_BACKEND_UNSUPPORTED"
    PUBLISHED_EXPERT_SLUG_TAKEN = "PUBLISHED_EXPERT_SLUG_TAKEN"
    PUBLISHED_EXPERT_ALREADY_EXISTS = "PUBLISHED_EXPERT_ALREADY_EXISTS"
    OIDC_BAD_REQUEST = "OIDC_BAD_REQUEST"
    SSO_IDENTITY_TAKEN = "SSO_IDENTITY_TAKEN"
    SSO_UNBIND_REQUIRES_PASSWORD = "SSO_UNBIND_REQUIRES_PASSWORD"
    EXPERT_MARKET_FAILED = "EXPERT_MARKET_FAILED"
    SKILLHUB_SSL_FAILED = "SKILLHUB_SSL_FAILED"
    DESKTOP_SESSION_LIMIT = "DESKTOP_SESSION_LIMIT"
    DESKTOP_CAPTURE_FAILED = "DESKTOP_CAPTURE_FAILED"
    PLUGIN_INVALID_ARCHIVE = "PLUGIN_INVALID_ARCHIVE"
    PLUGIN_INSTALL_FAILED = "PLUGIN_INSTALL_FAILED"
    PLUGIN_ALREADY_EXISTS = "PLUGIN_ALREADY_EXISTS"
    KNOWLEDGE_FEATURE_DISABLED = "KNOWLEDGE_FEATURE_DISABLED"
    KNOWLEDGE_PREREQUISITES_FAILED = "KNOWLEDGE_PREREQUISITES_FAILED"
    KNOWLEDGE_NOT_FOUND = "KNOWLEDGE_NOT_FOUND"
    KNOWLEDGE_FORBIDDEN = "KNOWLEDGE_FORBIDDEN"
    KNOWLEDGE_DOC_LIMIT = "KNOWLEDGE_DOC_LIMIT"
    KNOWLEDGE_DOC_TOO_LARGE = "KNOWLEDGE_DOC_TOO_LARGE"
    KNOWLEDGE_BASE_LIMIT = "KNOWLEDGE_BASE_LIMIT"
    KNOWLEDGE_UNSUPPORTED_TYPE = "KNOWLEDGE_UNSUPPORTED_TYPE"
    KNOWLEDGE_NAME_TAKEN = "KNOWLEDGE_NAME_TAKEN"
    KNOWLEDGE_NAME_INVALID = "KNOWLEDGE_NAME_INVALID"
    AVATAR_INVALID = "AVATAR_INVALID"
    AVATAR_TOO_LARGE = "AVATAR_TOO_LARGE"
    INVITE_INVALID = "INVITE_INVALID"
    INVITE_USED = "INVITE_USED"
    INVITE_EXPIRED = "INVITE_EXPIRED"
    INVITE_REVOKED = "INVITE_REVOKED"
    INVITE_RATE_LIMITED = "INVITE_RATE_LIMITED"
    WORKSPACE_ROOT_RESTRICTED = "WORKSPACE_ROOT_RESTRICTED"
    WORKSPACE_ROOT_CONTAINER_UNSUPPORTED = "WORKSPACE_ROOT_CONTAINER_UNSUPPORTED"
    TOKEN_QUOTA_EXCEEDED = "TOKEN_QUOTA_EXCEEDED"
    # WorkBuddy tenant identity and governance.,
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    WORKBUDDY_POSTGRES_REQUIRED = "WORKBUDDY_POSTGRES_REQUIRED"
    WORKBUDDY_CONTEXT_INVALID = "WORKBUDDY_CONTEXT_INVALID"
    WORKBUDDY_INVALID_ARGUMENT = "WORKBUDDY_INVALID_ARGUMENT"
    WORKBUDDY_MEMBERSHIP_REQUIRED = "WORKBUDDY_MEMBERSHIP_REQUIRED"
    WORKBUDDY_TENANT_MISMATCH = "WORKBUDDY_TENANT_MISMATCH"
    WORKBUDDY_TENANT_SUSPENDED = "WORKBUDDY_TENANT_SUSPENDED"
    WORKBUDDY_MEMBER_DISABLED = "WORKBUDDY_MEMBER_DISABLED"
    WORKBUDDY_PLATFORM_AUDIENCE_REQUIRED = "WORKBUDDY_PLATFORM_AUDIENCE_REQUIRED"
    WORKBUDDY_TENANT_SLUG_TAKEN = "WORKBUDDY_TENANT_SLUG_TAKEN"
    WORKBUDDY_MEMBERSHIP_EXISTS = "WORKBUDDY_MEMBERSHIP_EXISTS"
    WORKBUDDY_LAST_OWNER_REQUIRED = "WORKBUDDY_LAST_OWNER_REQUIRED"
    WORKBUDDY_DEPARTMENT_NAME_TAKEN = "WORKBUDDY_DEPARTMENT_NAME_TAKEN"
    WORKBUDDY_DEPARTMENT_CYCLE = "WORKBUDDY_DEPARTMENT_CYCLE"
    WORKBUDDY_DEPARTMENT_DEPTH_EXCEEDED = "WORKBUDDY_DEPARTMENT_DEPTH_EXCEEDED"
    WORKBUDDY_QUOTA_EXCEEDED = "WORKBUDDY_QUOTA_EXCEEDED"
    WORKBUDDY_QUOTA_METRIC_INVALID = "WORKBUDDY_QUOTA_METRIC_INVALID"
    WORKBUDDY_INVITATION_INVALID = "WORKBUDDY_INVITATION_INVALID"
    WORKBUDDY_INVITATION_EXPIRED = "WORKBUDDY_INVITATION_EXPIRED"
    WORKBUDDY_INVITATION_REVOKED = "WORKBUDDY_INVITATION_REVOKED"
    WORKBUDDY_INVITATION_ALREADY_ACCEPTED = "WORKBUDDY_INVITATION_ALREADY_ACCEPTED"
    WORKBUDDY_INVITATION_PENDING_EXISTS = "WORKBUDDY_INVITATION_PENDING_EXISTS"
    WORKBUDDY_SECRET_BACKEND_UNAVAILABLE = "WORKBUDDY_SECRET_BACKEND_UNAVAILABLE"
    WORKBUDDY_CATALOG_ERROR = "WORKBUDDY_CATALOG_ERROR"
    WORKBUDDY_INVALID_INPUT = "WORKBUDDY_INVALID_INPUT"
    WORKBUDDY_CREDENTIAL_REF_INVALID = "WORKBUDDY_CREDENTIAL_REF_INVALID"
    WORKBUDDY_CREDENTIAL_REVOKED = "WORKBUDDY_CREDENTIAL_REVOKED"
    WORKBUDDY_CREDENTIAL_REVISION_CONFLICT = "WORKBUDDY_CREDENTIAL_REVISION_CONFLICT"
    WORKBUDDY_CREDENTIAL_NAME_TAKEN = "WORKBUDDY_CREDENTIAL_NAME_TAKEN"
    WORKBUDDY_REVISION_CONFLICT = "WORKBUDDY_REVISION_CONFLICT"
    WORKBUDDY_REVISION_REVOKED = "WORKBUDDY_REVISION_REVOKED"
    WORKBUDDY_CAPABILITY_NOT_APPROVED = "WORKBUDDY_CAPABILITY_NOT_APPROVED"
    WORKBUDDY_CAPABILITY_NO_FIELDS = "WORKBUDDY_CAPABILITY_NO_FIELDS"
    WORKBUDDY_PLATFORM_REVISION_REVOKED = "WORKBUDDY_PLATFORM_REVISION_REVOKED"
    WORKBUDDY_PLATFORM_REVISION_CONFLICT = "WORKBUDDY_PLATFORM_REVISION_CONFLICT"
    WORKBUDDY_CAPABILITY_REVISION_CONFLICT = "WORKBUDDY_CAPABILITY_REVISION_CONFLICT"
    DOWNLOAD_GRANT_EXPIRED = "DOWNLOAD_GRANT_EXPIRED"
    # (export/deletion framework),
    # WorkBuddy workflow, runtime, knowledge, proposal, marketplace, and lifecycle errors.,
    APPROVAL_ALREADY_DECIDED = "APPROVAL_ALREADY_DECIDED"
    APPROVAL_BINDING_CHANGED = "APPROVAL_BINDING_CHANGED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVAL_NO_VALID_APPROVER = "APPROVAL_NO_VALID_APPROVER"
    APPROVAL_TOKEN_INVALID = "APPROVAL_TOKEN_INVALID"
    APPROVAL_VERSION_MISMATCH = "APPROVAL_VERSION_MISMATCH"
    ASK_NO_VALID_ASSIGNEE = "ASK_NO_VALID_ASSIGNEE"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_MISSING_TOKEN = "AUTH_MISSING_TOKEN"
    COMPLIANCE_GATE_CLOSED = "COMPLIANCE_GATE_CLOSED"
    DELETION_CANCEL_WINDOW_CLOSED = "DELETION_CANCEL_WINDOW_CLOSED"
    DELETION_REQUEST_CONFLICT = "DELETION_REQUEST_CONFLICT"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    EXPORT_JOB_NOT_FOUND = "EXPORT_JOB_NOT_FOUND"
    EXPORT_REDEEM_CONSUMED = "EXPORT_REDEEM_CONSUMED"
    EXPORT_REDEEM_EXPIRED = "EXPORT_REDEEM_EXPIRED"
    EXPORT_REDEEM_INVALID = "EXPORT_REDEEM_INVALID"
    FORBIDDEN_NOT_APPROVER = "FORBIDDEN_NOT_APPROVER"
    FORBIDDEN_RESOURCE_ACTION = "FORBIDDEN_RESOURCE_ACTION"
    FORBIDDEN_ROLE = "FORBIDDEN_ROLE"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED"
    INVALID_REQUEST = "INVALID_REQUEST"
    KB_MODEL_MISMATCH = "KB_MODEL_MISMATCH"
    KB_PARSE_FAILED = "KB_PARSE_FAILED"
    LEGAL_HOLD_ACTIVE = "LEGAL_HOLD_ACTIVE"
    MODEL_NOT_CONFIGURED = "MODEL_NOT_CONFIGURED"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    PRECONDITION_REQUIRED = "PRECONDITION_REQUIRED"
    PROPOSAL_BASE_CONFLICT = "PROPOSAL_BASE_CONFLICT"
    PROPOSAL_CANDIDATE_EXISTS = "PROPOSAL_CANDIDATE_EXISTS"
    PROPOSAL_GATE_NOT_MET = "PROPOSAL_GATE_NOT_MET"
    PROPOSAL_GOVERNANCE_REQUIRED = "PROPOSAL_GOVERNANCE_REQUIRED"
    PROPOSAL_PATCH_INVALID = "PROPOSAL_PATCH_INVALID"
    PROPOSAL_REVIEW_REQUIREMENT = "PROPOSAL_REVIEW_REQUIREMENT"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    RATE_LIMITED = "RATE_LIMITED"
    RECONCILIATION_EVIDENCE_INVALID = "RECONCILIATION_EVIDENCE_INVALID"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    STATE_CONFLICT = "STATE_CONFLICT"
    TENANT_NOT_ACTIVE = "TENANT_NOT_ACTIVE"
    TENANT_SUSPENDED = "TENANT_SUSPENDED"
    TRIGGER_PATH_CONFLICT = "TRIGGER_PATH_CONFLICT"
    TRIGGER_SIGNATURE_INVALID = "TRIGGER_SIGNATURE_INVALID"
    UPLOAD_NOT_READY = "UPLOAD_NOT_READY"
    WF_INVALID_SCHEMA = "WF_INVALID_SCHEMA"
    WF_LIMIT_EXCEEDED = "WF_LIMIT_EXCEEDED"
    WF_NO_ACTIVE_VERSION = "WF_NO_ACTIVE_VERSION"
    WF_VERSION_CONFLICT = "WF_VERSION_CONFLICT"
    WORKBUDDY_APPROVAL_INVALID = "WORKBUDDY_APPROVAL_INVALID"
    WORKBUDDY_APPROVAL_NOT_CONFIGURED = "WORKBUDDY_APPROVAL_NOT_CONFIGURED"
    WORKBUDDY_CONSENT_REQUIRED = "WORKBUDDY_CONSENT_REQUIRED"
    WORKBUDDY_DEPENDENCY_UNAVAILABLE = "WORKBUDDY_DEPENDENCY_UNAVAILABLE"
    WORKBUDDY_EXECUTION_NOT_CANCELLABLE = "WORKBUDDY_EXECUTION_NOT_CANCELLABLE"
    WORKBUDDY_EXECUTION_NOT_RESUMABLE = "WORKBUDDY_EXECUTION_NOT_RESUMABLE"
    WORKBUDDY_FENCE_STALE = "WORKBUDDY_FENCE_STALE"
    WORKBUDDY_IDEMPOTENCY_CONFLICT = "WORKBUDDY_IDEMPOTENCY_CONFLICT"
    WORKBUDDY_LICENSE_NOT_ACCEPTED = "WORKBUDDY_LICENSE_NOT_ACCEPTED"
    WORKBUDDY_MARKETPLACE_NOT_FOUND = "WORKBUDDY_MARKETPLACE_NOT_FOUND"
    WORKBUDDY_MODEL_NOT_CONFIGURED = "WORKBUDDY_MODEL_NOT_CONFIGURED"
    WORKBUDDY_PRECONDITION_REQUIRED = "WORKBUDDY_PRECONDITION_REQUIRED"
    WORKBUDDY_REBINDING_INCOMPLETE = "WORKBUDDY_REBINDING_INCOMPLETE"
    WORKBUDDY_RECONCILIATION_CONFLICT = "WORKBUDDY_RECONCILIATION_CONFLICT"
    WORKBUDDY_SUBMISSION_FROZEN = "WORKBUDDY_SUBMISSION_FROZEN"
    WORKBUDDY_SUBMISSION_INVALID = "WORKBUDDY_SUBMISSION_INVALID"
    WORKBUDDY_SUBMISSION_NOT_APPROVABLE = "WORKBUDDY_SUBMISSION_NOT_APPROVABLE"
    WORKBUDDY_TEMPLATE_VERSION_NOT_INSTALLABLE = "WORKBUDDY_TEMPLATE_VERSION_NOT_INSTALLABLE"
    WORKBUDDY_VALIDATION_FAILED = "WORKBUDDY_VALIDATION_FAILED"
    WORKBUDDY_VERSION_IMMUTABLE = "WORKBUDDY_VERSION_IMMUTABLE"
    WORKBUDDY_WORKFLOW_INVALID = "WORKBUDDY_WORKFLOW_INVALID"
    WORKBUDDY_WORKFLOW_REVISION_CONFLICT = "WORKBUDDY_WORKFLOW_REVISION_CONFLICT"
    WORKBUDDY_WORKFLOW_VERSION_NOT_ACTIVATABLE = "WORKBUDDY_WORKFLOW_VERSION_NOT_ACTIVATABLE"
    WORKBUDDY_WORKFLOW_VERSION_NOT_FOUND = "WORKBUDDY_WORKFLOW_VERSION_NOT_FOUND"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    CAPTCHA_FAILED = "CAPTCHA_FAILED"
    CONFIG_FILE_CORRUPT = "CONFIG_FILE_CORRUPT"


_DEFAULT_STATUS: dict[ErrorCode, int] = {
    ErrorCode.AUTH_FAILED: 401,
    ErrorCode.TOKEN_EXPIRED: 401,
    ErrorCode.SETUP_REQUIRED: 409,
    ErrorCode.DATABASE_NOT_EMPTY: 409,
    ErrorCode.BACKUP_DRIVER_MISMATCH: 400,
    ErrorCode.BACKUP_SCHEMA_INCOMPATIBLE: 400,
    ErrorCode.BACKUP_IN_PROGRESS: 409,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.USER_DISABLED: 403,
    ErrorCode.LOGIN_LOCKED: 429,
    ErrorCode.USERNAME_TAKEN: 409,
    ErrorCode.EMAIL_TAKEN: 409,
    ErrorCode.EMAIL_INVALID: 400,
    ErrorCode.PASSWORD_SAME_AS_OLD: 400,
    ErrorCode.PASSWORD_TOO_WEAK: 400,
    ErrorCode.SETUP_PASSWORD_WRONG: 401,
    ErrorCode.SETUP_RATE_LIMITED: 429,
    ErrorCode.SETUP_TOKEN_INVALID: 401,
    ErrorCode.AGENT_NOT_FOUND: 404,
    ErrorCode.AGENT_NOT_RUNNING: 409,
    ErrorCode.AGENT_FAILED: 500,
    ErrorCode.AGENT_BUSY: 409,
    ErrorCode.AGENT_NAME_TAKEN: 409,
    ErrorCode.AGENT_ID_INVALID: 400,
    ErrorCode.AGENT_ID_TAKEN: 409,
    ErrorCode.PROVIDER_NAME_TAKEN: 409,
    ErrorCode.PROVIDER_NOT_VISIBLE: 400,
    ErrorCode.PROVIDER_REFERENCED: 409,
    ErrorCode.PROVIDER_LOCAL_PROTECTED: 409,
    ErrorCode.STORAGE_BACKEND_NAME_TAKEN: 409,
    ErrorCode.STORAGE_BACKEND_REFERENCED: 409,
    ErrorCode.STORAGE_BACKEND_DEPS_FAILED: 503,
    ErrorCode.CHANNEL_KIND_UNSUPPORTED: 400,
    ErrorCode.CHANNEL_INVALID_CREDENTIALS: 400,
    ErrorCode.CHANNEL_NAME_TAKEN: 409,
    ErrorCode.CONNECTOR_NOT_FOUND: 404,
    ErrorCode.CONNECTOR_NAME_TAKEN: 409,
    ErrorCode.CONNECTOR_INVALID_CREDENTIALS: 400,
    ErrorCode.CONNECTOR_OAUTH_HTTPS_REQUIRED: 400,
    ErrorCode.CONNECTOR_KIND_UNSUPPORTED: 400,
    ErrorCode.CONNECTOR_NOT_BOUND: 400,
    ErrorCode.CONNECTOR_ALREADY_BOUND: 409,
    ErrorCode.CONNECTOR_MCP_LOAD_FAILED: 502,
    ErrorCode.CRON_TRIGGER_INVALID: 400,
    ErrorCode.SLASH_UNKNOWN: 400,
    ErrorCode.SLASH_BAD_ARGS: 400,
    ErrorCode.ATTACHMENT_UNSUPPORTED_TYPE: 400,
    ErrorCode.ATTACHMENT_TOO_LARGE: 413,
    ErrorCode.VOICE_BROWSER_ONLY: 422,
    ErrorCode.VOICE_KIND_UNSUPPORTED: 400,
    ErrorCode.VOICE_CAPABILITY_MISMATCH: 400,
    ErrorCode.VOICE_PROVIDER_DISABLED: 400,
    ErrorCode.INTERNAL_ERROR: 500,
    ErrorCode.TLS_NOT_ELIGIBLE: 403,
    ErrorCode.TLS_ISSUE_IN_PROGRESS: 409,
    ErrorCode.TLS_DOMAIN_MISMATCH: 400,
    ErrorCode.WORKSPACE_OP_UNSUPPORTED: 400,
    ErrorCode.SKILL_IMPORT_UNSUPPORTED_URL: 400,
    ErrorCode.SKILL_IMPORT_FAILED: 502,
    ErrorCode.SKILL_ALREADY_EXISTS: 409,
    ErrorCode.SKILL_PACKAGE_NOT_FOUND: 404,
    ErrorCode.SKILL_PACKAGE_NAME_TAKEN: 409,
    ErrorCode.SKILL_PACKAGE_BACKEND_UNSUPPORTED: 400,
    ErrorCode.PUBLISHED_EXPERT_SLUG_TAKEN: 409,
    ErrorCode.PUBLISHED_EXPERT_ALREADY_EXISTS: 409,
    ErrorCode.OIDC_BAD_REQUEST: 400,
    ErrorCode.SSO_IDENTITY_TAKEN: 409,
    ErrorCode.SSO_UNBIND_REQUIRES_PASSWORD: 400,
    ErrorCode.EXPERT_MARKET_FAILED: 502,
    ErrorCode.SKILLHUB_SSL_FAILED: 502,
    ErrorCode.DESKTOP_SESSION_LIMIT: 429,
    ErrorCode.DESKTOP_CAPTURE_FAILED: 503,
    ErrorCode.PLUGIN_INVALID_ARCHIVE: 400,
    ErrorCode.PLUGIN_INSTALL_FAILED: 502,
    ErrorCode.PLUGIN_ALREADY_EXISTS: 409,
    ErrorCode.KNOWLEDGE_FEATURE_DISABLED: 403,
    ErrorCode.KNOWLEDGE_PREREQUISITES_FAILED: 409,
    ErrorCode.KNOWLEDGE_NOT_FOUND: 404,
    ErrorCode.KNOWLEDGE_FORBIDDEN: 403,
    ErrorCode.KNOWLEDGE_DOC_LIMIT: 409,
    ErrorCode.KNOWLEDGE_DOC_TOO_LARGE: 413,
    ErrorCode.KNOWLEDGE_BASE_LIMIT: 409,
    ErrorCode.KNOWLEDGE_UNSUPPORTED_TYPE: 400,
    ErrorCode.KNOWLEDGE_NAME_TAKEN: 409,
    ErrorCode.KNOWLEDGE_NAME_INVALID: 400,
    ErrorCode.AVATAR_INVALID: 400,
    ErrorCode.AVATAR_TOO_LARGE: 413,
    ErrorCode.INVITE_INVALID: 400,
    ErrorCode.INVITE_USED: 409,
    ErrorCode.INVITE_EXPIRED: 410,
    ErrorCode.INVITE_REVOKED: 410,
    ErrorCode.INVITE_RATE_LIMITED: 429,
    ErrorCode.WORKSPACE_ROOT_RESTRICTED: 400,
    ErrorCode.WORKSPACE_ROOT_CONTAINER_UNSUPPORTED: 400,
    ErrorCode.TOKEN_QUOTA_EXCEEDED: 403,
    ErrorCode.AUTH_INVALID_CREDENTIALS: 401,
    ErrorCode.WORKBUDDY_POSTGRES_REQUIRED: 503,
    ErrorCode.WORKBUDDY_CONTEXT_INVALID: 400,
    ErrorCode.WORKBUDDY_INVALID_ARGUMENT: 400,
    ErrorCode.WORKBUDDY_MEMBERSHIP_REQUIRED: 403,
    ErrorCode.WORKBUDDY_TENANT_MISMATCH: 403,
    ErrorCode.WORKBUDDY_TENANT_SUSPENDED: 403,
    ErrorCode.WORKBUDDY_MEMBER_DISABLED: 403,
    ErrorCode.WORKBUDDY_PLATFORM_AUDIENCE_REQUIRED: 403,
    ErrorCode.WORKBUDDY_TENANT_SLUG_TAKEN: 409,
    ErrorCode.WORKBUDDY_MEMBERSHIP_EXISTS: 409,
    ErrorCode.WORKBUDDY_LAST_OWNER_REQUIRED: 409,
    ErrorCode.WORKBUDDY_DEPARTMENT_NAME_TAKEN: 409,
    ErrorCode.WORKBUDDY_DEPARTMENT_CYCLE: 409,
    ErrorCode.WORKBUDDY_DEPARTMENT_DEPTH_EXCEEDED: 400,
    ErrorCode.WORKBUDDY_QUOTA_EXCEEDED: 409,
    ErrorCode.WORKBUDDY_QUOTA_METRIC_INVALID: 400,
    ErrorCode.WORKBUDDY_INVITATION_INVALID: 400,
    ErrorCode.WORKBUDDY_INVITATION_EXPIRED: 410,
    ErrorCode.WORKBUDDY_INVITATION_REVOKED: 409,
    ErrorCode.WORKBUDDY_INVITATION_ALREADY_ACCEPTED: 409,
    ErrorCode.WORKBUDDY_INVITATION_PENDING_EXISTS: 409,
    ErrorCode.WORKBUDDY_SECRET_BACKEND_UNAVAILABLE: 503,
    ErrorCode.WORKBUDDY_CATALOG_ERROR: 400,
    ErrorCode.WORKBUDDY_INVALID_INPUT: 400,
    ErrorCode.WORKBUDDY_CREDENTIAL_REF_INVALID: 400,
    ErrorCode.WORKBUDDY_CREDENTIAL_REVOKED: 409,
    ErrorCode.WORKBUDDY_CREDENTIAL_REVISION_CONFLICT: 409,
    ErrorCode.WORKBUDDY_CREDENTIAL_NAME_TAKEN: 409,
    ErrorCode.WORKBUDDY_REVISION_CONFLICT: 409,
    ErrorCode.WORKBUDDY_REVISION_REVOKED: 409,
    ErrorCode.WORKBUDDY_CAPABILITY_NOT_APPROVED: 403,
    ErrorCode.WORKBUDDY_CAPABILITY_NO_FIELDS: 400,
    ErrorCode.WORKBUDDY_PLATFORM_REVISION_REVOKED: 409,
    ErrorCode.WORKBUDDY_PLATFORM_REVISION_CONFLICT: 409,
    ErrorCode.WORKBUDDY_CAPABILITY_REVISION_CONFLICT: 409,
    ErrorCode.DOWNLOAD_GRANT_EXPIRED: 410,
    ErrorCode.APPROVAL_ALREADY_DECIDED: 409,
    ErrorCode.APPROVAL_BINDING_CHANGED: 409,
    ErrorCode.APPROVAL_EXPIRED: 410,
    ErrorCode.APPROVAL_NO_VALID_APPROVER: 422,
    ErrorCode.ASK_NO_VALID_ASSIGNEE: 422,
    ErrorCode.APPROVAL_TOKEN_INVALID: 403,
    ErrorCode.APPROVAL_VERSION_MISMATCH: 409,
    ErrorCode.AUTH_INVALID_TOKEN: 401,
    ErrorCode.AUTH_MISSING_TOKEN: 401,
    ErrorCode.COMPLIANCE_GATE_CLOSED: 503,
    ErrorCode.DELETION_CANCEL_WINDOW_CLOSED: 409,
    ErrorCode.DELETION_REQUEST_CONFLICT: 409,
    ErrorCode.DEPENDENCY_UNAVAILABLE: 503,
    ErrorCode.EXPORT_JOB_NOT_FOUND: 404,
    ErrorCode.EXPORT_REDEEM_CONSUMED: 409,
    ErrorCode.EXPORT_REDEEM_EXPIRED: 410,
    ErrorCode.EXPORT_REDEEM_INVALID: 404,
    ErrorCode.FORBIDDEN_NOT_APPROVER: 403,
    ErrorCode.FORBIDDEN_RESOURCE_ACTION: 403,
    ErrorCode.FORBIDDEN_ROLE: 403,
    ErrorCode.IDEMPOTENCY_CONFLICT: 409,
    ErrorCode.IDEMPOTENCY_KEY_REQUIRED: 400,
    ErrorCode.INVALID_REQUEST: 400,
    ErrorCode.KB_MODEL_MISMATCH: 422,
    ErrorCode.KB_PARSE_FAILED: 422,
    ErrorCode.LEGAL_HOLD_ACTIVE: 409,
    ErrorCode.MODEL_NOT_CONFIGURED: 503,
    ErrorCode.PAYLOAD_TOO_LARGE: 413,
    ErrorCode.PRECONDITION_REQUIRED: 428,
    ErrorCode.PROPOSAL_BASE_CONFLICT: 409,
    ErrorCode.PROPOSAL_CANDIDATE_EXISTS: 409,
    ErrorCode.PROPOSAL_GATE_NOT_MET: 409,
    ErrorCode.PROPOSAL_GOVERNANCE_REQUIRED: 409,
    ErrorCode.PROPOSAL_PATCH_INVALID: 422,
    ErrorCode.PROPOSAL_REVIEW_REQUIREMENT: 409,
    ErrorCode.QUOTA_EXCEEDED: 429,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.RECONCILIATION_EVIDENCE_INVALID: 422,
    ErrorCode.RECONCILIATION_REQUIRED: 409,
    ErrorCode.RESOURCE_NOT_FOUND: 404,
    ErrorCode.STATE_CONFLICT: 409,
    ErrorCode.TENANT_NOT_ACTIVE: 403,
    ErrorCode.TENANT_SUSPENDED: 403,
    ErrorCode.TRIGGER_PATH_CONFLICT: 422,
    ErrorCode.TRIGGER_SIGNATURE_INVALID: 403,
    ErrorCode.UPLOAD_NOT_READY: 409,
    ErrorCode.WF_INVALID_SCHEMA: 422,
    ErrorCode.WF_LIMIT_EXCEEDED: 422,
    ErrorCode.WF_NO_ACTIVE_VERSION: 409,
    ErrorCode.WF_VERSION_CONFLICT: 409,
    ErrorCode.WORKBUDDY_APPROVAL_INVALID: 409,
    ErrorCode.WORKBUDDY_APPROVAL_NOT_CONFIGURED: 409,
    ErrorCode.WORKBUDDY_CONSENT_REQUIRED: 400,
    ErrorCode.WORKBUDDY_DEPENDENCY_UNAVAILABLE: 503,
    ErrorCode.WORKBUDDY_EXECUTION_NOT_CANCELLABLE: 409,
    ErrorCode.WORKBUDDY_EXECUTION_NOT_RESUMABLE: 409,
    ErrorCode.WORKBUDDY_FENCE_STALE: 409,
    ErrorCode.WORKBUDDY_IDEMPOTENCY_CONFLICT: 409,
    ErrorCode.WORKBUDDY_LICENSE_NOT_ACCEPTED: 400,
    ErrorCode.WORKBUDDY_MARKETPLACE_NOT_FOUND: 404,
    ErrorCode.WORKBUDDY_MODEL_NOT_CONFIGURED: 503,
    ErrorCode.WORKBUDDY_PRECONDITION_REQUIRED: 428,
    ErrorCode.WORKBUDDY_REBINDING_INCOMPLETE: 400,
    ErrorCode.WORKBUDDY_RECONCILIATION_CONFLICT: 409,
    ErrorCode.WORKBUDDY_SUBMISSION_FROZEN: 409,
    ErrorCode.WORKBUDDY_SUBMISSION_INVALID: 400,
    ErrorCode.WORKBUDDY_SUBMISSION_NOT_APPROVABLE: 409,
    ErrorCode.WORKBUDDY_TEMPLATE_VERSION_NOT_INSTALLABLE: 409,
    ErrorCode.WORKBUDDY_VALIDATION_FAILED: 400,
    ErrorCode.WORKBUDDY_VERSION_IMMUTABLE: 409,
    ErrorCode.WORKBUDDY_WORKFLOW_INVALID: 422,
    ErrorCode.WORKBUDDY_WORKFLOW_REVISION_CONFLICT: 409,
    ErrorCode.WORKBUDDY_WORKFLOW_VERSION_NOT_ACTIVATABLE: 409,
    ErrorCode.WORKBUDDY_WORKFLOW_VERSION_NOT_FOUND: 404,
    ErrorCode.CAPTCHA_REQUIRED: 400,
    ErrorCode.CAPTCHA_FAILED: 400,
    ErrorCode.CONFIG_FILE_CORRUPT: 400,
}


@dataclass
class OctopError(Exception):
    code: ErrorCode
    message: str
    status: int = 0
    details: dict[str, Any] = field(default_factory=dict)
    # Some refusals must reach the client with headers, not only a body: a
    # rate-limited answer carries Retry-After and the X-RateLimit-* set.
    headers: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.status == 0:
            self.status = _DEFAULT_STATUS[self.code]
        super().__init__(self.message)

    def localized_message(self, locale: str | Locale, **kwargs: object) -> str:
        loc = normalize_locale(str(locale))
        try:
            return i18n_error_message(self.code.value, loc, **{**self.details, **kwargs})
        except KeyError:
            return self.message

    @classmethod
    def localized(
        cls,
        code: ErrorCode,
        locale: str | Locale = "en",
        *,
        message: str | None = None,
        status: int = 0,
        details: dict[str, Any] | None = None,
        **kwargs: object,
    ) -> OctopError:
        msg = (
            message
            if message is not None
            else i18n_error_message(code.value, normalize_locale(str(locale)), **kwargs)
        )
        return cls(code, msg, status=status, details=details or {})

    def to_envelope(self, *, locale: str | Locale | None = None) -> dict[str, Any]:
        message = self.localized_message(locale) if locale is not None else self.message
        return {
            "error": {
                "code": self.code.value,
                "message": message,
                "details": self.details,
            }
        }


def corrupt_config_error(path: object, detail: str) -> OctopError:
    """``OctopError`` for a config file that exists but cannot be parsed.

    Raised instead of writing back a merged-into-empty dict, which would destroy
    every unrelated setting (issue #730). Carries the path and the parser
    position only — never file contents, which hold database credentials.
    """
    return OctopError(
        ErrorCode.CONFIG_FILE_CORRUPT,
        f"{path} is not valid JSON ({detail}); fix it and retry — no settings were changed",
        details={"path": str(path), "detail": detail},
    )
